### ISSUE TITLE
HTTP Client Decoupling

### ISSUE THREAD

**Issue by jimpeters** [dbellettini/php-eventstore-client#11]
I would like to refactor to decouple Guzzle as a required dependency and introduce a HTTP client interface that can be switched out.  In a high volume system I would rather use persistent sockets for example which will allow me to keep pace with the speed of EventStore.  While testing I can maintain 1000 requests per second with persistent sockets but only 200-250 a second with Guzzle on the same machine.  

This also makes it easier to test the EventStore class in isolation and allow for dependency injection.

I would be more than happy to write this change, just want to get feedback on what everyone thinks first.

interface EventStore\Http\Client

$client = new EventStore\Http\Guzzle($uri);
$es = new EventStore\EventStore(Client $client);

$client = new EventStore\Http\PersistentSockets($uri);
$es = new EventStore\EventStore(Client $client);

$client = new EventStore\Http\Curl($uri);
$es = new EventStore\EventStore(Client $client);

**Comment by dbellettini** [comment]
will discuss this after february 16th

**Comment by dbellettini** [comment]
sorry for postponing many times, but I'm busy with university in the spare time.

Can you please post an example with PersistentSockets?

**Comment by dbellettini** [comment]
What about waiting for PSR-7?
