### ISSUE TITLE
EventType wrong when reading projections

### ISSUE THREAD

**Issue by Akii** [dbellettini/php-eventstore-client#13]
This is due to the fact that the summary field contains anything but the EventType ("$>") when reading streams that are based on projections. The events (and the data) itself are fetched normally.

A possible solution to this problem is to set the feeds embed mode to FULL and fix the `EventStore\StreamFeed\Entry::getType()` like this:

```
return (isset($this->json['eventType'])) ? $this->json['eventType'] : $this->json['summary'];
```

Should this be an acceptable solution, I'd gladly provide a pull-request.

**Comment by mrsimonbennett** [comment]
+1

**Comment by dbellettini** [comment]
can you please post a code example or better a failing PHPUnit test case?
