### ISSUE TITLE
Remove Broadway integration

### ISSUE THREAD

**Issue by Akii** [dbellettini/php-eventstore-client#16]
Broadway should integrate with the eventstore-client, like the symfony package does. I don't know the reason why it was designed like this, but eventually this should be reversed.

I'd gladly provide a pull-request to both packages. Additionally, the implementation of the Broadway repository is flawed since the order of events is wrong (newest events come first).

**Comment by dbellettini** [comment]
Ok, I'll extract its history using filter-branch and create a new repository for it. Stay tuned

**Comment by Akii** [comment]
I have talked to the guys from Broadway in the meantime, they agreed to this and actually wanted to contact you guys about this. So we're good to go! Not sure if I can get it done today, but certainly within tomorrow.
