### ISSUE TITLE
Client does not catch 404 responses for deleted Events

### ISSUE THREAD

**Issue by Akii** [dbellettini/php-eventstore-client#17]
So I've deleted a stream and the EventStore continues to serve the deleted events in my projections. At the moment I'm not sure how to exclude them from the projections but this results in an empty response that should be handled by the client.

```
Catchable Fatal Error: Argument 1 passed to EventStore\StreamFeed\Event::__construct()
must be of the type array, null given, called in
.../dbellettini/eventstore-client/src/EventStore/EventStore.php on line 124
```

A possible solution would be to simply return NULL instead of the Event if the `$jsonResponse` is NULL.

```
 $jsonResponse = $this->lastResponse->json();

if ($jsonResponse === NULL) {
	return NULL;
}
		
return new Event($jsonResponse);
```

This would be a breaking change though. Any suggestions / ideas?

**Comment by mrsimonbennett** [comment]
I can confirm this issue
  Argument 1 passed to EventStore\StreamFeed\Event::__construct() must be of the type array, null given, called in /var/www/vendor/dbellettini/eventstore-client/src/EventStore/EventStore.php on line 124 and defined

**Comment by dbellettini** [comment]
I would prefer an EmptyBodyException or something like that /cc @nicolopignatelli 

@mrsimonbennett which version of this client are you using?

**Comment by Akii** [comment]
Also fine, thanks for fixing.

**Comment by dbellettini** [comment]
In this case it will give StreamNotFoundException on soft delete and StreamDeletedException on hard delete

**Comment by Akii** [comment]
Just checked to make sure you can actually catch those exceptions. This is definitely a better solution.
