### ISSUE TITLE
Build TCP Client

### ISSUE THREAD

**Issue by dgafka** [dbellettini/php-eventstore-client#29]
Build on top of https://github.com/madkom/event-store-client TCP Client, which is much faster than standard HTTP one.

Example usage:
$esAsync = new EventStoreAsync('http://127.0.0.1:1113');
$esSync = new EventStoreSync('http://127.0.0.1:2113');

**Comment by dbellettini** [comment]
I'm not sure we can have a proper way to abstract the underlying protocol, @nicolopignatelli what do you think? However I'll have a look during christmas holydays
